package Gamejam;

import javafx.geometry.Insets;
import javafx.scene.image.Image;
import javafx.scene.layout.Background;
import javafx.scene.layout.BackgroundFill;
import javafx.scene.layout.Border;
import javafx.scene.layout.BorderStroke;
import javafx.scene.layout.BorderStrokeStyle;
import javafx.scene.layout.BorderWidths;
import javafx.scene.layout.CornerRadii;
import javafx.scene.paint.Color;
import javafx.scene.paint.CycleMethod;
import javafx.scene.paint.LinearGradient;
import javafx.scene.paint.Paint;
import javafx.scene.paint.Stop;
/**
 * A class full of solely static methods.
 * Houses the Pre-set Dynamicly generated themes!
 * @author Joey McMaster
 *
 */
public class ThemeGenerate {
	public static Theme createThemeGenerated_USA() {
	    Theme retval = new Theme("USA Theme",80);
	    return retval;
	}
	/**
	 * Generated by the Theme Creator, a full code dump of a theme.
	 * @return A fully set up theme for single click use.
	 */
	public static Theme createThemeGenerated_Night() {
	    Theme retval = new Theme("Night Theme", 80);
	    return retval;
	}
}
